---
driver:
  name: vagrant
driver_config:
  # http_proxy: http://webproxysea.nordstrom.net:8181
  # https_proxy: http://webproxysea.nordstrom.net:8181
  require_chef_omnibus: false

provisioner:
  name: chef_solo

platforms:
  - name: nordsol10
    driver:
      box: nordsol10
      box_url: http://y0319p297/downloads/vagrant-solaris10.box
  - name: nordsol11
    driver:
      box: nordsol11
      box_url: http://y0319p297/downloads/vagrant-solaris11.box

suites:
  - name: install
    run_list:
      - recipe[smf::default]
      - recipe[test_smf::smf_install]
    attributes:
